services:
    zikulaintercommodule.form.type.message:
        class: Zikula\IntercomModule\Form\Type\MessageType
        tags:
            - { name: form.type, alias: messageform }
    zikulaintercommodule.link_container:
        class: Zikula\IntercomModule\Container\LinkContainer
        lazy: true
        tags:
            - { name: zikula.link_container }
        arguments: [@router, @translator]
    zikulaintercommodule.access_manager:
        class: Zikula\IntercomModule\Security\AccessManager
